# If you are having problems with wires randomly not appearing,
# try to enable this feature. It will cause wires respawn with
# delay, after they were sent to a player.
# This can cause slight client lag on chunk loading in older versions,
# if you have too many wires in one place, especially thick wires.
enableWireResend: false

# If enableWireResend does not fix problems with wires not appearing,
# you can enable continious respawn. All wires will be continiously
# respawned while visible to a player. This may cause client lags
# in older versions. Do not use on 1.8.
continiousRespawn:
  enabled: false
  # Respawn interval in ticks (1 tick = 1 / 20 of a sec).
  interval: 100

# Modules of the plugin implement different features.
modules:
  # Lead placement module allows players to place wires using lead item.
  leadPlacement:
    # If false, lead placement will be disabled.
    enabled: true
    # Max length of the lead. If exceeded, player will receive a message.
    maxLength: 10
    # If true, player can continue placing leads after placing one,
    # new lead will start from second point of the last lead.
    continueFromLastPoint: true
    # Permission to place leads. If empty, permission will not be checked.
    # If permission is set and player has no such permission, player will receive a message.
    permission: ''
    # All blocks allowing a lead to be placed on them.
    # This list works both for the legacy (1.12-) and flattened (1.13+) versions.
    allowedBlocks:
      - 'FENCE'
      - 'OAK_FENCE'
      - 'SPRUCE_FENCE'
      - 'BIRCH_FENCE'
      - 'JUNGLE_FENCE'
      - 'ACACIA_FENCE'
      - 'DARK_OAK_FENCE'
      - 'COBBLE_WALL'
      - 'COBBLESTONE_WALL'
      - 'MOSSY_COBBLESTONE_WALL'
      - 'BRICK_WALL'
      - 'PRISMARINE_WALL'
      - 'RED_SANDSTONE_WALL'
      - 'MOSSY_STONE_BRICK_WALL'
      - 'GRANITE_WALL'
      - 'STONE_BRICK_WALL'
      - 'NETHER_BRICK_WALL'
      - 'ANDESITE_WALL'
      - 'RED_NETHER_BRICK_WALL'
      - 'SANDSTONE_WALL'
      - 'END_STONE_BRICK_WALL'
      - 'DIORITE_WALL'
    # Messages sent to players.
    messages:
      firstPointSet: '<green>First point of the lead set'
      firstPointReset: '<gray>First point has been reset'
      wirePlaced: '<green>The lead has been placed'
      tooLong: '<red>The lead is too long, limit is <param1> blocks'
      noPermission: '<red>You have no permission to place leads'